### ISSUE TITLE
get_all_users( ) not working

### ISSUE THREAD

**Issue by fnokeke** [hfaran/piazza-api#30]
Hi, 
Testing out your api and it's nice. Thanks for making it pretty straightforward. 

I've got an issue with get_all_users returning the error below: 

RequestError: Could not get users.
Response: {
  "aid": "iduiwc98geh5e0", 
  "error_codes": [], 
  "result": null, 
  "error": "Do not have permission"
}

I'm a student of one of the classes I was querying. I was wondering if the get_all_users( ) function is only open to instructors. 

Thanks

**Comment by arxanas** [comment]
My assumption would be that it's not allowable for non-instructors. There might be FERPA concerns (in the US) about disclosing who's taking a class. I believe the provided information is kind of invasive — I think it includes email address? — so it wouldn't be appropriate for a student to access it.

As a workaround, you could try crawling all of the posts and collecting the usernames you see.

**Comment by fnokeke** [comment]
That makes sense. I tried with a username that has admin right and was able to retrieve all users. 
Thanks

**Comment by hfaran** [comment]
@arxanas is correct. One way you could get close to `get_all_users` is iterating over the entire class feed and compiling a list of usernames, but, it isn't the full list of users unless everyone has posted at least once (which doesn't give you what you want).

Only teachers have permission to view all users.
